name: deploy
on:
  push:
    branches:
      - main
env:
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Build Site & Update
        working-directory: ./
        run: |
          npm install
          npm run build
          npm run update
      - name: Deploy
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.FTP_DEPLOY_HOST }}
          username: ${{ secrets.FTP_DEPLOY_USERNAME }}
          password: ${{ secrets.FTP_DEPLOY_PASSWORD }}
          port: ${{ secrets.FTP_DEPLOY_PORT }}
          uploads: |
            ./_site => ./sites/blog/
